name: Coverage report

on:
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: Produce Coverage report
        uses: ./
        with:
          path: coverage/cobertura-coverage.xml
          branch_minimum_threshold: 90